# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_audio_note.ui'
#
# Created: Wed Nov 20 11:05:11 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FrameArchiveNote(object):
    def setupUi(self, FrameArchiveNote):
        FrameArchiveNote.setObjectName(_fromUtf8("FrameArchiveNote"))
        FrameArchiveNote.setWindowModality(QtCore.Qt.NonModal)
        FrameArchiveNote.resize(423, 443)
        FrameArchiveNote.setFrameShape(QtGui.QFrame.StyledPanel)
        FrameArchiveNote.setFrameShadow(QtGui.QFrame.Raised)
        self.groupBox = QtGui.QGroupBox(FrameArchiveNote)
        self.groupBox.setGeometry(QtCore.QRect(4, 8, 413, 401))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label.setObjectName(_fromUtf8("label"))
        self.edtToneMemo = QtGui.QTextEdit(self.groupBox)
        self.edtToneMemo.setGeometry(QtCore.QRect(78, 284, 321, 77))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.edtToneMemo.setFont(font)
        self.edtToneMemo.setObjectName(_fromUtf8("edtToneMemo"))
        self.edtClientName = QtGui.QLineEdit(self.groupBox)
        self.edtClientName.setGeometry(QtCore.QRect(78, 44, 261, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.edtClientName.setFont(font)
        self.edtClientName.setObjectName(_fromUtf8("edtClientName"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 54, 12))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(16, 284, 54, 37))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 54, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.edtToneAttr = QtGui.QLineEdit(self.groupBox)
        self.edtToneAttr.setGeometry(QtCore.QRect(78, 80, 320, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.edtToneAttr.setFont(font)
        self.edtToneAttr.setObjectName(_fromUtf8("edtToneAttr"))
        self.edtPhone = QtGui.QLineEdit(self.groupBox)
        self.edtPhone.setGeometry(QtCore.QRect(78, 50, 320, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.edtPhone.setFont(font)
        self.edtPhone.setObjectName(_fromUtf8("edtPhone"))
        self.edtToneTime = QtGui.QLineEdit(self.groupBox)
        self.edtToneTime.setGeometry(QtCore.QRect(78, 110, 320, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.edtToneTime.setFont(font)
        self.edtToneTime.setObjectName(_fromUtf8("edtToneTime"))
        self.labToneTime = QtGui.QLabel(self.groupBox)
        self.labToneTime.setGeometry(QtCore.QRect(20, 110, 54, 12))
        self.labToneTime.setObjectName(_fromUtf8("labToneTime"))
        self.btnSelectClient = QtGui.QPushButton(self.groupBox)
        self.btnSelectClient.setGeometry(QtCore.QRect(348, 16, 51, 23))
        self.btnSelectClient.setObjectName(_fromUtf8("btnSelectClient"))
        self.cbxToneType = QtGui.QComboBox(self.groupBox)
        self.cbxToneType.setGeometry(QtCore.QRect(78, 140, 317, 22))
        self.cbxToneType.setObjectName(_fromUtf8("cbxToneType"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(16, 144, 54, 12))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(12, 176, 54, 12))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.edtProductId = QtGui.QLineEdit(self.groupBox)
        self.edtProductId.setGeometry(QtCore.QRect(78, 172, 320, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.edtProductId.setFont(font)
        self.edtProductId.setMaxLength(30)
        self.edtProductId.setObjectName(_fromUtf8("edtProductId"))
        self.cbxClientNames = QtGui.QComboBox(self.groupBox)
        self.cbxClientNames.setGeometry(QtCore.QRect(80, 16, 257, 22))
        self.cbxClientNames.setEditable(True)
        self.cbxClientNames.setObjectName(_fromUtf8("cbxClientNames"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(1, 369, 69, 16))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cbxCurrOperator = QtGui.QComboBox(self.groupBox)
        self.cbxCurrOperator.setGeometry(QtCore.QRect(78, 368, 157, 22))
        self.cbxCurrOperator.setEditable(True)
        self.cbxCurrOperator.setObjectName(_fromUtf8("cbxCurrOperator"))
        self.edtHistoryToneMemoList = QtGui.QTextEdit(self.groupBox)
        self.edtHistoryToneMemoList.setGeometry(QtCore.QRect(78, 200, 321, 77))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.edtHistoryToneMemoList.setFont(font)
        self.edtHistoryToneMemoList.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.edtHistoryToneMemoList.setReadOnly(True)
        self.edtHistoryToneMemoList.setObjectName(_fromUtf8("edtHistoryToneMemoList"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 196, 54, 37))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.btnSave = QtGui.QPushButton(FrameArchiveNote)
        self.btnSave.setGeometry(QtCore.QRect(116, 412, 75, 23))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.btnClose = QtGui.QPushButton(FrameArchiveNote)
        self.btnClose.setGeometry(QtCore.QRect(236, 412, 75, 23))
        self.btnClose.setObjectName(_fromUtf8("btnClose"))

        self.retranslateUi(FrameArchiveNote)
        QtCore.QMetaObject.connectSlotsByName(FrameArchiveNote)

    def retranslateUi(self, FrameArchiveNote):
        FrameArchiveNote.setWindowTitle(_translate("FrameArchiveNote", "语音备注信息", None))
        self.label.setText(_translate("FrameArchiveNote", "客户名称", None))
        self.label_2.setText(_translate("FrameArchiveNote", "电话号码", None))
        self.label_6.setText(_translate("FrameArchiveNote", "通话备注\n"
"", None))
        self.label_3.setText(_translate("FrameArchiveNote", "录音类型", None))
        self.labToneTime.setText(_translate("FrameArchiveNote", "通话时间", None))
        self.btnSelectClient.setText(_translate("FrameArchiveNote", "选择", None))
        self.label_5.setText(_translate("FrameArchiveNote", "通话类型", None))
        self.label_7.setText(_translate("FrameArchiveNote", "产品ID", None))
        self.label_8.setText(_translate("FrameArchiveNote", "客户经理", None))
        self.label_9.setText(_translate("FrameArchiveNote", "历史备注", None))
        self.btnSave.setText(_translate("FrameArchiveNote", "保 存", None))
        self.btnClose.setText(_translate("FrameArchiveNote", "取 消", None))

