# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_client_info.ui'
#
# Created: Sun Dec 08 02:27:04 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FrameClientInfo(object):
    def setupUi(self, FrameClientInfo):
        FrameClientInfo.setObjectName(_fromUtf8("FrameClientInfo"))
        FrameClientInfo.setWindowModality(QtCore.Qt.WindowModal)
        FrameClientInfo.resize(357, 540)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        FrameClientInfo.setFont(font)
        FrameClientInfo.setFrameShape(QtGui.QFrame.StyledPanel)
        FrameClientInfo.setFrameShadow(QtGui.QFrame.Raised)
        self.btnSave = QtGui.QPushButton(FrameClientInfo)
        self.btnSave.setGeometry(QtCore.QRect(150, 513, 75, 23))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.label = QtGui.QLabel(FrameClientInfo)
        self.label.setGeometry(QtCore.QRect(10, 28, 54, 12))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.edtName = QtGui.QLineEdit(FrameClientInfo)
        self.edtName.setGeometry(QtCore.QRect(79, 25, 260, 20))
        self.edtName.setMaxLength(30)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.label_2 = QtGui.QLabel(FrameClientInfo)
        self.label_2.setGeometry(QtCore.QRect(10, 57, 54, 12))
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cbxSex = QtGui.QComboBox(FrameClientInfo)
        self.cbxSex.setGeometry(QtCore.QRect(80, 50, 260, 22))
        self.cbxSex.setObjectName(_fromUtf8("cbxSex"))
        self.label_3 = QtGui.QLabel(FrameClientInfo)
        self.label_3.setGeometry(QtCore.QRect(10, 176, 54, 12))
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.edtCorp = QtGui.QLineEdit(FrameClientInfo)
        self.edtCorp.setGeometry(QtCore.QRect(80, 170, 260, 20))
        self.edtCorp.setMaxLength(30)
        self.edtCorp.setObjectName(_fromUtf8("edtCorp"))
        self.label_4 = QtGui.QLabel(FrameClientInfo)
        self.label_4.setGeometry(QtCore.QRect(10, 206, 54, 12))
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.edtPhone1 = QtGui.QLineEdit(FrameClientInfo)
        self.edtPhone1.setGeometry(QtCore.QRect(80, 200, 260, 20))
        self.edtPhone1.setMaxLength(30)
        self.edtPhone1.setObjectName(_fromUtf8("edtPhone1"))
        self.label_5 = QtGui.QLabel(FrameClientInfo)
        self.label_5.setGeometry(QtCore.QRect(10, 236, 54, 12))
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.edtPhone2 = QtGui.QLineEdit(FrameClientInfo)
        self.edtPhone2.setGeometry(QtCore.QRect(80, 230, 260, 20))
        self.edtPhone2.setMaxLength(30)
        self.edtPhone2.setObjectName(_fromUtf8("edtPhone2"))
        self.label_7 = QtGui.QLabel(FrameClientInfo)
        self.label_7.setGeometry(QtCore.QRect(10, 325, 54, 12))
        self.label_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.edtAddress = QtGui.QLineEdit(FrameClientInfo)
        self.edtAddress.setGeometry(QtCore.QRect(80, 320, 260, 20))
        self.edtAddress.setMaxLength(60)
        self.edtAddress.setObjectName(_fromUtf8("edtAddress"))
        self.edtPostCode = QtGui.QLineEdit(FrameClientInfo)
        self.edtPostCode.setGeometry(QtCore.QRect(80, 350, 260, 20))
        self.edtPostCode.setMaxLength(30)
        self.edtPostCode.setObjectName(_fromUtf8("edtPostCode"))
        self.label_8 = QtGui.QLabel(FrameClientInfo)
        self.label_8.setGeometry(QtCore.QRect(10, 355, 54, 12))
        self.label_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.edtMail = QtGui.QLineEdit(FrameClientInfo)
        self.edtMail.setGeometry(QtCore.QRect(80, 379, 260, 20))
        self.edtMail.setMaxLength(30)
        self.edtMail.setObjectName(_fromUtf8("edtMail"))
        self.label_9 = QtGui.QLabel(FrameClientInfo)
        self.label_9.setGeometry(QtCore.QRect(10, 385, 54, 12))
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_12 = QtGui.QLabel(FrameClientInfo)
        self.label_12.setGeometry(QtCore.QRect(10, 443, 54, 12))
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.edtMemo = QtGui.QTextEdit(FrameClientInfo)
        self.edtMemo.setGeometry(QtCore.QRect(80, 436, 260, 71))
        self.edtMemo.setObjectName(_fromUtf8("edtMemo"))
        self.label_6 = QtGui.QLabel(FrameClientInfo)
        self.label_6.setGeometry(QtCore.QRect(10, 86, 54, 12))
        self.label_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.edtPersonId = QtGui.QLineEdit(FrameClientInfo)
        self.edtPersonId.setGeometry(QtCore.QRect(80, 140, 260, 20))
        self.edtPersonId.setMaxLength(30)
        self.edtPersonId.setObjectName(_fromUtf8("edtPersonId"))
        self.label_13 = QtGui.QLabel(FrameClientInfo)
        self.label_13.setGeometry(QtCore.QRect(10, 146, 54, 12))
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.edtClientId = QtGui.QLineEdit(FrameClientInfo)
        self.edtClientId.setGeometry(QtCore.QRect(80, 80, 260, 20))
        self.edtClientId.setMaxLength(30)
        self.edtClientId.setObjectName(_fromUtf8("edtClientId"))
        self.edtPhone3 = QtGui.QLineEdit(FrameClientInfo)
        self.edtPhone3.setGeometry(QtCore.QRect(80, 259, 260, 20))
        self.edtPhone3.setMaxLength(30)
        self.edtPhone3.setObjectName(_fromUtf8("edtPhone3"))
        self.edtOwnerOrg = QtGui.QLineEdit(FrameClientInfo)
        self.edtOwnerOrg.setGeometry(QtCore.QRect(80, 290, 260, 20))
        self.edtOwnerOrg.setMaxLength(30)
        self.edtOwnerOrg.setObjectName(_fromUtf8("edtOwnerOrg"))
        self.label_11 = QtGui.QLabel(FrameClientInfo)
        self.label_11.setGeometry(QtCore.QRect(10, 115, 54, 12))
        self.label_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_10 = QtGui.QLabel(FrameClientInfo)
        self.label_10.setGeometry(QtCore.QRect(10, 265, 54, 12))
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.cbxType = QtGui.QComboBox(FrameClientInfo)
        self.cbxType.setGeometry(QtCore.QRect(80, 110, 260, 22))
        self.cbxType.setObjectName(_fromUtf8("cbxType"))
        self.label_14 = QtGui.QLabel(FrameClientInfo)
        self.label_14.setGeometry(QtCore.QRect(10, 293, 54, 12))
        self.label_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(FrameClientInfo)
        self.label_15.setGeometry(QtCore.QRect(0, 408, 73, 16))
        self.label_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.edtCustomTag = QtGui.QLineEdit(FrameClientInfo)
        self.edtCustomTag.setGeometry(QtCore.QRect(80, 408, 260, 20))
        self.edtCustomTag.setMaxLength(50)
        self.edtCustomTag.setObjectName(_fromUtf8("edtCustomTag"))

        self.retranslateUi(FrameClientInfo)
        QtCore.QMetaObject.connectSlotsByName(FrameClientInfo)

    def retranslateUi(self, FrameClientInfo):
        FrameClientInfo.setWindowTitle(_translate("FrameClientInfo", "客户信息", None))
        self.btnSave.setText(_translate("FrameClientInfo", "保 存", None))
        self.label.setText(_translate("FrameClientInfo", "客户名称", None))
        self.label_2.setText(_translate("FrameClientInfo", "性别", None))
        self.label_3.setText(_translate("FrameClientInfo", "公司", None))
        self.label_4.setText(_translate("FrameClientInfo", "电话-1", None))
        self.label_5.setText(_translate("FrameClientInfo", "电话-2", None))
        self.label_7.setText(_translate("FrameClientInfo", "地址", None))
        self.label_8.setText(_translate("FrameClientInfo", "邮政编码", None))
        self.label_9.setText(_translate("FrameClientInfo", "邮件", None))
        self.label_12.setText(_translate("FrameClientInfo", "备注", None))
        self.label_6.setText(_translate("FrameClientInfo", "客户号", None))
        self.label_13.setText(_translate("FrameClientInfo", "身份证", None))
        self.label_11.setText(_translate("FrameClientInfo", "客户类别", None))
        self.label_10.setText(_translate("FrameClientInfo", "电话-3", None))
        self.label_14.setText(_translate("FrameClientInfo", "归属机构", None))
        self.label_15.setText(_translate("FrameClientInfo", "自定义标签", None))

