# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created: Wed Nov 20 11:05:10 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(835, 472)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabStatus = QtGui.QWidget()
        self.tabStatus.setObjectName(_fromUtf8("tabStatus"))
        self.label = QtGui.QLabel(self.tabStatus)
        self.label.setGeometry(QtCore.QRect(-32, 92, 125, 16))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tabStatus)
        self.label_2.setGeometry(QtCore.QRect(-32, 124, 125, 16))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.btnCheckVersion = QtGui.QPushButton(self.tabStatus)
        self.btnCheckVersion.setGeometry(QtCore.QRect(108, 244, 97, 32))
        self.btnCheckVersion.setObjectName(_fromUtf8("btnCheckVersion"))
        self.txtStatus = QtGui.QLabel(self.tabStatus)
        self.txtStatus.setGeometry(QtCore.QRect(116, 88, 440, 25))
        self.txtStatus.setFrameShape(QtGui.QFrame.StyledPanel)
        self.txtStatus.setFrameShadow(QtGui.QFrame.Plain)
        self.txtStatus.setText(_fromUtf8(""))
        self.txtStatus.setObjectName(_fromUtf8("txtStatus"))
        self.txtVersion = QtGui.QLabel(self.tabStatus)
        self.txtVersion.setGeometry(QtCore.QRect(116, 124, 440, 21))
        self.txtVersion.setFrameShape(QtGui.QFrame.StyledPanel)
        self.txtVersion.setText(_fromUtf8(""))
        self.txtVersion.setObjectName(_fromUtf8("txtVersion"))
        self.label_21 = QtGui.QLabel(self.tabStatus)
        self.label_21.setGeometry(QtCore.QRect(-32, 160, 125, 16))
        self.label_21.setScaledContents(False)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.txtPhoneStatus = QtGui.QLabel(self.tabStatus)
        self.txtPhoneStatus.setGeometry(QtCore.QRect(116, 160, 440, 21))
        self.txtPhoneStatus.setFrameShape(QtGui.QFrame.StyledPanel)
        self.txtPhoneStatus.setObjectName(_fromUtf8("txtPhoneStatus"))
        self.label_23 = QtGui.QLabel(self.tabStatus)
        self.label_23.setGeometry(QtCore.QRect(-32, 196, 125, 16))
        self.label_23.setScaledContents(False)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.txtDiskResource = QtGui.QLabel(self.tabStatus)
        self.txtDiskResource.setGeometry(QtCore.QRect(116, 192, 440, 21))
        self.txtDiskResource.setFrameShape(QtGui.QFrame.StyledPanel)
        self.txtDiskResource.setText(_fromUtf8(""))
        self.txtDiskResource.setObjectName(_fromUtf8("txtDiskResource"))
        self.btnOpenMediaDir = QtGui.QPushButton(self.tabStatus)
        self.btnOpenMediaDir.setGeometry(QtCore.QRect(220, 244, 97, 32))
        self.btnOpenMediaDir.setObjectName(_fromUtf8("btnOpenMediaDir"))
        self.tabWidget.addTab(self.tabStatus, _fromUtf8(""))
        self.tabClients = QtGui.QWidget()
        self.tabClients.setObjectName(_fromUtf8("tabClients"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabClients)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setMargin(2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(self.tabClients)
        self.widget.setMinimumSize(QtCore.QSize(0, 60))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.cbxClientQueryTypes = QtGui.QComboBox(self.widget)
        self.cbxClientQueryTypes.setGeometry(QtCore.QRect(40, 8, 125, 22))
        self.cbxClientQueryTypes.setObjectName(_fromUtf8("cbxClientQueryTypes"))
        self.edtClientQueryContent = QtGui.QLineEdit(self.widget)
        self.edtClientQueryContent.setGeometry(QtCore.QRect(172, 8, 229, 20))
        self.edtClientQueryContent.setObjectName(_fromUtf8("edtClientQueryContent"))
        self.btnClientQuery = QtGui.QPushButton(self.widget)
        self.btnClientQuery.setGeometry(QtCore.QRect(616, 8, 75, 23))
        self.btnClientQuery.setObjectName(_fromUtf8("btnClientQuery"))
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(4, 12, 37, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.btnClientDelete = QtGui.QPushButton(self.widget)
        self.btnClientDelete.setGeometry(QtCore.QRect(208, 36, 75, 23))
        self.btnClientDelete.setObjectName(_fromUtf8("btnClientDelete"))
        self.btnClientNew = QtGui.QPushButton(self.widget)
        self.btnClientNew.setGeometry(QtCore.QRect(40, 36, 75, 23))
        self.btnClientNew.setObjectName(_fromUtf8("btnClientNew"))
        self.btnClientEdit = QtGui.QPushButton(self.widget)
        self.btnClientEdit.setGeometry(QtCore.QRect(124, 36, 75, 23))
        self.btnClientEdit.setObjectName(_fromUtf8("btnClientEdit"))
        self.btnDial = QtGui.QPushButton(self.widget)
        self.btnDial.setGeometry(QtCore.QRect(324, 36, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDial.setFont(font)
        self.btnDial.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.btnDial.setObjectName(_fromUtf8("btnDial"))
        self.btnHangup = QtGui.QPushButton(self.widget)
        self.btnHangup.setGeometry(QtCore.QRect(408, 36, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnHangup.setFont(font)
        self.btnHangup.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.btnHangup.setObjectName(_fromUtf8("btnHangup"))
        self.label_22 = QtGui.QLabel(self.widget)
        self.label_22.setGeometry(QtCore.QRect(420, 12, 57, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.cbxClientType = QtGui.QComboBox(self.widget)
        self.cbxClientType.setGeometry(QtCore.QRect(476, 8, 125, 22))
        self.cbxClientType.setObjectName(_fromUtf8("cbxClientType"))
        self.btnSceneRecordStart = QtGui.QPushButton(self.widget)
        self.btnSceneRecordStart.setGeometry(QtCore.QRect(532, 36, 75, 23))
        self.btnSceneRecordStart.setObjectName(_fromUtf8("btnSceneRecordStart"))
        self.btnSceneRecordStop = QtGui.QPushButton(self.widget)
        self.btnSceneRecordStop.setGeometry(QtCore.QRect(616, 36, 75, 23))
        self.btnSceneRecordStop.setObjectName(_fromUtf8("btnSceneRecordStop"))
        self.verticalLayout.addWidget(self.widget)
        self.tvClientList = QtGui.QTreeWidget(self.tabClients)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tvClientList.setFont(font)
        self.tvClientList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvClientList.setObjectName(_fromUtf8("tvClientList"))
        self.tvClientList.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.tvClientList)
        self.widget_2 = QtGui.QWidget(self.tabClients)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 5))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tabClients, _fromUtf8(""))
        self.tabArchives = QtGui.QWidget()
        self.tabArchives.setObjectName(_fromUtf8("tabArchives"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabArchives)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setMargin(3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget_3 = QtGui.QWidget(self.tabArchives)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 74))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.widget_3)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 2, 865, 72))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(0, 44, 54, 12))
        self.label_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.cbxToneAttrs = QtGui.QComboBox(self.groupBox_5)
        self.cbxToneAttrs.setGeometry(QtCore.QRect(552, 7, 92, 22))
        self.cbxToneAttrs.setObjectName(_fromUtf8("cbxToneAttrs"))
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(212, 44, 16, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_14 = QtGui.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(472, 12, 77, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(4, 12, 53, 16))
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.btnToneQuery = QtGui.QPushButton(self.groupBox_5)
        self.btnToneQuery.setGeometry(QtCore.QRect(716, 38, 93, 25))
        self.btnToneQuery.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.btnToneQuery.setObjectName(_fromUtf8("btnToneQuery"))
        self.edtToneQueryContent = QtGui.QLineEdit(self.groupBox_5)
        self.edtToneQueryContent.setGeometry(QtCore.QRect(224, 9, 217, 20))
        self.edtToneQueryContent.setObjectName(_fromUtf8("edtToneQueryContent"))
        self.cbxToneQueryTypes = QtGui.QComboBox(self.groupBox_5)
        self.cbxToneQueryTypes.setGeometry(QtCore.QRect(64, 8, 140, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbxToneQueryTypes.setFont(font)
        self.cbxToneQueryTypes.setObjectName(_fromUtf8("cbxToneQueryTypes"))
        self.dtToneStart = QtGui.QDateTimeEdit(self.groupBox_5)
        self.dtToneStart.setGeometry(QtCore.QRect(64, 40, 140, 25))
        self.dtToneStart.setCalendarPopup(True)
        self.dtToneStart.setObjectName(_fromUtf8("dtToneStart"))
        self.dtToneEnd = QtGui.QDateTimeEdit(self.groupBox_5)
        self.dtToneEnd.setGeometry(QtCore.QRect(224, 40, 140, 25))
        self.dtToneEnd.setCalendarPopup(True)
        self.dtToneEnd.setObjectName(_fromUtf8("dtToneEnd"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(364, 44, 153, 16))
        self.label_17.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.edtToneQueryMemo = QtGui.QLineEdit(self.groupBox_5)
        self.edtToneQueryMemo.setGeometry(QtCore.QRect(508, 42, 201, 20))
        self.edtToneQueryMemo.setObjectName(_fromUtf8("edtToneQueryMemo"))
        self.btnRecordDial = QtGui.QPushButton(self.groupBox_5)
        self.btnRecordDial.setGeometry(QtCore.QRect(-20, 60, 75, 23))
        self.btnRecordDial.setObjectName(_fromUtf8("btnRecordDial"))
        self.cbxToneType = QtGui.QComboBox(self.groupBox_5)
        self.cbxToneType.setGeometry(QtCore.QRect(716, 8, 92, 22))
        self.cbxToneType.setObjectName(_fromUtf8("cbxToneType"))
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(656, 13, 54, 12))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_4.addWidget(self.widget_3)
        self.tvToneList = QtGui.QTreeWidget(self.tabArchives)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tvToneList.setFont(font)
        self.tvToneList.setObjectName(_fromUtf8("tvToneList"))
        self.tvToneList.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_4.addWidget(self.tvToneList)
        self.widget_4 = QtGui.QWidget(self.tabArchives)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.groupBox_4 = QtGui.QGroupBox(self.widget_4)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 809, 77))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.btnNext = QtGui.QPushButton(self.groupBox_4)
        self.btnNext.setGeometry(QtCore.QRect(172, 0, 24, 22))
        self.btnNext.setText(_fromUtf8(""))
        self.btnNext.setObjectName(_fromUtf8("btnNext"))
        self.btnPause = QtGui.QPushButton(self.groupBox_4)
        self.btnPause.setGeometry(QtCore.QRect(45, 16, 28, 24))
        self.btnPause.setText(_fromUtf8(""))
        self.btnPause.setFlat(False)
        self.btnPause.setObjectName(_fromUtf8("btnPause"))
        self.btnPlay = QtGui.QPushButton(self.groupBox_4)
        self.btnPlay.setGeometry(QtCore.QRect(18, 16, 28, 24))
        self.btnPlay.setText(_fromUtf8(""))
        self.btnPlay.setFlat(False)
        self.btnPlay.setObjectName(_fromUtf8("btnPlay"))
        self.btnStop = QtGui.QPushButton(self.groupBox_4)
        self.btnStop.setGeometry(QtCore.QRect(72, 16, 28, 24))
        self.btnStop.setText(_fromUtf8(""))
        self.btnStop.setObjectName(_fromUtf8("btnStop"))
        self.btnBack = QtGui.QPushButton(self.groupBox_4)
        self.btnBack.setGeometry(QtCore.QRect(149, 0, 24, 22))
        self.btnBack.setText(_fromUtf8(""))
        self.btnBack.setObjectName(_fromUtf8("btnBack"))
        self.txtPlayIndicator = QtGui.QLabel(self.groupBox_4)
        self.txtPlayIndicator.setGeometry(QtCore.QRect(144, 48, 137, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtPlayIndicator.setFont(font)
        self.txtPlayIndicator.setObjectName(_fromUtf8("txtPlayIndicator"))
        self.seekSlider = phonon.Phonon.SeekSlider(self.groupBox_4)
        self.seekSlider.setGeometry(QtCore.QRect(140, 20, 641, 21))
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.groupBox_4)
        self.volumeSlider.setGeometry(QtCore.QRect(16, 48, 109, 22))
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.btnToneMemo = QtGui.QPushButton(self.groupBox_4)
        self.btnToneMemo.setGeometry(QtCore.QRect(708, 45, 75, 23))
        self.btnToneMemo.setObjectName(_fromUtf8("btnToneMemo"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(282, 53, 54, 12))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.txtToneTime = QtGui.QLabel(self.groupBox_4)
        self.txtToneTime.setGeometry(QtCore.QRect(340, 48, 145, 21))
        self.txtToneTime.setFrameShape(QtGui.QFrame.StyledPanel)
        self.txtToneTime.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtToneTime.setText(_fromUtf8(""))
        self.txtToneTime.setObjectName(_fromUtf8("txtToneTime"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(497, 54, 54, 12))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.txtTonePhone = QtGui.QLabel(self.groupBox_4)
        self.txtTonePhone.setGeometry(QtCore.QRect(552, 48, 145, 21))
        self.txtTonePhone.setFrameShape(QtGui.QFrame.StyledPanel)
        self.txtTonePhone.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtTonePhone.setText(_fromUtf8(""))
        self.txtTonePhone.setObjectName(_fromUtf8("txtTonePhone"))
        self.verticalLayout_4.addWidget(self.widget_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tabArchives, _fromUtf8(""))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.groupBox = QtGui.QGroupBox(self.tabSettings)
        self.groupBox.setGeometry(QtCore.QRect(8, 20, 325, 109))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 26, 54, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.edtUser = QtGui.QLineEdit(self.groupBox)
        self.edtUser.setGeometry(QtCore.QRect(92, 20, 217, 20))
        self.edtUser.setStyleSheet(_fromUtf8(""))
        self.edtUser.setText(_fromUtf8(""))
        self.edtUser.setMaxLength(30)
        self.edtUser.setObjectName(_fromUtf8("edtUser"))
        self.edtPasswd = QtGui.QLineEdit(self.groupBox)
        self.edtPasswd.setGeometry(QtCore.QRect(92, 48, 217, 20))
        self.edtPasswd.setStyleSheet(_fromUtf8(""))
        self.edtPasswd.setMaxLength(20)
        self.edtPasswd.setEchoMode(QtGui.QLineEdit.Password)
        self.edtPasswd.setObjectName(_fromUtf8("edtPasswd"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 54, 54, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.btnChangePasswd = QtGui.QPushButton(self.groupBox)
        self.btnChangePasswd.setGeometry(QtCore.QRect(92, 76, 75, 23))
        self.btnChangePasswd.setObjectName(_fromUtf8("btnChangePasswd"))
        self.txtRegStatus = QtGui.QLabel(self.groupBox)
        self.txtRegStatus.setGeometry(QtCore.QRect(188, 80, 117, 16))
        self.txtRegStatus.setObjectName(_fromUtf8("txtRegStatus"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabSettings)
        self.groupBox_2.setGeometry(QtCore.QRect(364, 16, 445, 253))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 58, 54, 12))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.edtPhone = QtGui.QLineEdit(self.groupBox_2)
        self.edtPhone.setGeometry(QtCore.QRect(92, 52, 341, 20))
        self.edtPhone.setStyleSheet(_fromUtf8(""))
        self.edtPhone.setMaxLength(40)
        self.edtPhone.setObjectName(_fromUtf8("edtPhone"))
        self.edtEmployee = QtGui.QLineEdit(self.groupBox_2)
        self.edtEmployee.setGeometry(QtCore.QRect(92, 80, 341, 20))
        self.edtEmployee.setStyleSheet(_fromUtf8(""))
        self.edtEmployee.setMaxLength(20)
        self.edtEmployee.setEchoMode(QtGui.QLineEdit.Normal)
        self.edtEmployee.setObjectName(_fromUtf8("edtEmployee"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 86, 54, 12))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 114, 54, 12))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.edtAddress = QtGui.QLineEdit(self.groupBox_2)
        self.edtAddress.setGeometry(QtCore.QRect(92, 108, 341, 20))
        self.edtAddress.setStyleSheet(_fromUtf8(""))
        self.edtAddress.setMaxLength(120)
        self.edtAddress.setEchoMode(QtGui.QLineEdit.Normal)
        self.edtAddress.setObjectName(_fromUtf8("edtAddress"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 160, 54, 12))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.edtAddition = QtGui.QTextEdit(self.groupBox_2)
        self.edtAddition.setGeometry(QtCore.QRect(92, 136, 341, 71))
        self.edtAddition.setStyleSheet(_fromUtf8(""))
        self.edtAddition.setObjectName(_fromUtf8("edtAddition"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(-56, 24, 125, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.txtOrganization = QtGui.QLabel(self.groupBox_2)
        self.txtOrganization.setGeometry(QtCore.QRect(92, 20, 341, 25))
        self.txtOrganization.setFrameShape(QtGui.QFrame.StyledPanel)
        self.txtOrganization.setFrameShadow(QtGui.QFrame.Plain)
        self.txtOrganization.setText(_fromUtf8(""))
        self.txtOrganization.setObjectName(_fromUtf8("txtOrganization"))
        self.btnUpdateTermInfo = QtGui.QPushButton(self.groupBox_2)
        self.btnUpdateTermInfo.setGeometry(QtCore.QRect(92, 216, 97, 23))
        self.btnUpdateTermInfo.setObjectName(_fromUtf8("btnUpdateTermInfo"))
        self.btnSave = QtGui.QPushButton(self.tabSettings)
        self.btnSave.setGeometry(QtCore.QRect(16, 360, 75, 23))
        self.btnSave.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 255, 127);"))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabSettings)
        self.groupBox_3.setGeometry(QtCore.QRect(8, 140, 325, 85))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 42, 69, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.edtServer1 = QtGui.QLineEdit(self.groupBox_3)
        self.edtServer1.setGeometry(QtCore.QRect(92, 40, 221, 20))
        self.edtServer1.setStyleSheet(_fromUtf8(""))
        self.edtServer1.setObjectName(_fromUtf8("edtServer1"))
        self.edtServer2 = QtGui.QLineEdit(self.groupBox_3)
        self.edtServer2.setGeometry(QtCore.QRect(92, 63, 221, 20))
        self.edtServer2.setStyleSheet(_fromUtf8(""))
        self.edtServer2.setObjectName(_fromUtf8("edtServer2"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(20, 64, 54, 12))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.ckAutoStartWithOsStart = QtGui.QCheckBox(self.tabSettings)
        self.ckAutoStartWithOsStart.setGeometry(QtCore.QRect(368, 292, 181, 16))
        self.ckAutoStartWithOsStart.setObjectName(_fromUtf8("ckAutoStartWithOsStart"))
        self.ckAutoLogin = QtGui.QCheckBox(self.tabSettings)
        self.ckAutoLogin.setEnabled(False)
        self.ckAutoLogin.setGeometry(QtCore.QRect(256, 140, 71, 16))
        self.ckAutoLogin.setObjectName(_fromUtf8("ckAutoLogin"))
        self.btnLogin = QtGui.QPushButton(self.tabSettings)
        self.btnLogin.setEnabled(True)
        self.btnLogin.setGeometry(QtCore.QRect(152, 136, 75, 23))
        self.btnLogin.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 127);\n"
"background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);"))
        self.btnLogin.setObjectName(_fromUtf8("btnLogin"))
        self.ckRunInBackground = QtGui.QCheckBox(self.tabSettings)
        self.ckRunInBackground.setGeometry(QtCore.QRect(368, 320, 181, 16))
        self.ckRunInBackground.setObjectName(_fromUtf8("ckRunInBackground"))
        self.groupBox_6 = QtGui.QGroupBox(self.tabSettings)
        self.groupBox_6.setGeometry(QtCore.QRect(12, 236, 321, 80))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(12, 30, 69, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.edtPhonePasswd = QtGui.QLineEdit(self.groupBox_6)
        self.edtPhonePasswd.setGeometry(QtCore.QRect(84, 28, 221, 20))
        self.edtPhonePasswd.setStyleSheet(_fromUtf8(""))
        self.edtPhonePasswd.setInputMask(_fromUtf8(""))
        self.edtPhonePasswd.setText(_fromUtf8(""))
        self.edtPhonePasswd.setMaxLength(32767)
        self.edtPhonePasswd.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.edtPhonePasswd.setObjectName(_fromUtf8("edtPhonePasswd"))
        self.txtPhonePasswdStatus = QtGui.QLabel(self.groupBox_6)
        self.txtPhonePasswdStatus.setGeometry(QtCore.QRect(84, 52, 217, 16))
        self.txtPhonePasswdStatus.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.txtPhonePasswdStatus.setText(_fromUtf8(""))
        self.txtPhonePasswdStatus.setTextFormat(QtCore.Qt.AutoText)
        self.txtPhonePasswdStatus.setObjectName(_fromUtf8("txtPhonePasswdStatus"))
        self.cbxLockTimes = QtGui.QComboBox(self.tabSettings)
        self.cbxLockTimes.setGeometry(QtCore.QRect(732, 292, 77, 22))
        self.cbxLockTimes.setObjectName(_fromUtf8("cbxLockTimes"))
        self.label_25 = QtGui.QLabel(self.tabSettings)
        self.label_25.setGeometry(QtCore.QRect(664, 296, 65, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.ckMemoAutoShow = QtGui.QCheckBox(self.tabSettings)
        self.ckMemoAutoShow.setGeometry(QtCore.QRect(368, 344, 153, 16))
        self.ckMemoAutoShow.setObjectName(_fromUtf8("ckMemoAutoShow"))
        self.tabWidget.addTab(self.tabSettings, _fromUtf8(""))
        self.tabRunLog = QtGui.QWidget()
        self.tabRunLog.setObjectName(_fromUtf8("tabRunLog"))
        self.edtLogMemo = QtGui.QTextEdit(self.tabRunLog)
        self.edtLogMemo.setGeometry(QtCore.QRect(12, 8, 661, 353))
        self.edtLogMemo.setObjectName(_fromUtf8("edtLogMemo"))
        self.tabWidget.addTab(self.tabRunLog, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 835, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_5 = QtGui.QMenu(self.menu)
        self.menu_5.setObjectName(_fromUtf8("menu_5"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menuBar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_4 = QtGui.QMenu(self.menuBar)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.menu_6 = QtGui.QMenu(self.menuBar)
        self.menu_6.setObjectName(_fromUtf8("menu_6"))
        MainWindow.setMenuBar(self.menuBar)
        self.miUserMgr = QtGui.QAction(MainWindow)
        self.miUserMgr.setObjectName(_fromUtf8("miUserMgr"))
        self.miTask = QtGui.QAction(MainWindow)
        self.miTask.setObjectName(_fromUtf8("miTask"))
        self.miServerStatus = QtGui.QAction(MainWindow)
        self.miServerStatus.setObjectName(_fromUtf8("miServerStatus"))
        self.miChangePwd = QtGui.QAction(MainWindow)
        self.miChangePwd.setObjectName(_fromUtf8("miChangePwd"))
        self.miExit = QtGui.QAction(MainWindow)
        self.miExit.setObjectName(_fromUtf8("miExit"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actClientImport = QtGui.QAction(MainWindow)
        self.actClientImport.setObjectName(_fromUtf8("actClientImport"))
        self.actClientExport = QtGui.QAction(MainWindow)
        self.actClientExport.setObjectName(_fromUtf8("actClientExport"))
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.action_6 = QtGui.QAction(MainWindow)
        self.action_6.setObjectName(_fromUtf8("action_6"))
        self.actTabStatus = QtGui.QAction(MainWindow)
        self.actTabStatus.setObjectName(_fromUtf8("actTabStatus"))
        self.actTabClient = QtGui.QAction(MainWindow)
        self.actTabClient.setObjectName(_fromUtf8("actTabClient"))
        self.actTabArchive = QtGui.QAction(MainWindow)
        self.actTabArchive.setObjectName(_fromUtf8("actTabArchive"))
        self.action_13 = QtGui.QAction(MainWindow)
        self.action_13.setObjectName(_fromUtf8("action_13"))
        self.actTabSettings = QtGui.QAction(MainWindow)
        self.actTabSettings.setObjectName(_fromUtf8("actTabSettings"))
        self.actAbout = QtGui.QAction(MainWindow)
        self.actAbout.setObjectName(_fromUtf8("actAbout"))
        self.actClientSyncFromServer = QtGui.QAction(MainWindow)
        self.actClientSyncFromServer.setObjectName(_fromUtf8("actClientSyncFromServer"))
        self.actSyncReset = QtGui.QAction(MainWindow)
        self.actSyncReset.setObjectName(_fromUtf8("actSyncReset"))
        self.actArchiveUnMatched = QtGui.QAction(MainWindow)
        self.actArchiveUnMatched.setObjectName(_fromUtf8("actArchiveUnMatched"))
        self.actArchiveUnMatchedMutli = QtGui.QAction(MainWindow)
        self.actArchiveUnMatchedMutli.setObjectName(_fromUtf8("actArchiveUnMatchedMutli"))
        self.actArchiveExport = QtGui.QAction(MainWindow)
        self.actArchiveExport.setObjectName(_fromUtf8("actArchiveExport"))
        self.actLockPasswdSetting = QtGui.QAction(MainWindow)
        self.actLockPasswdSetting.setObjectName(_fromUtf8("actLockPasswdSetting"))
        self.actLock = QtGui.QAction(MainWindow)
        self.actLock.setObjectName(_fromUtf8("actLock"))
        self.menu_5.addAction(self.actSyncReset)
        self.menu_5.addAction(self.actLockPasswdSetting)
        self.menu.addAction(self.menu_5.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.actLock)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actAbout)
        self.menu_3.addAction(self.actClientExport)
        self.menu_3.addAction(self.actClientImport)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actClientSyncFromServer)
        self.menu_4.addAction(self.actTabStatus)
        self.menu_4.addAction(self.actTabClient)
        self.menu_4.addAction(self.actTabArchive)
        self.menu_4.addAction(self.actTabSettings)
        self.menu_6.addAction(self.actArchiveUnMatched)
        self.menu_6.addAction(self.actArchiveUnMatchedMutli)
        self.menu_6.addSeparator()
        self.menu_6.addAction(self.actArchiveExport)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_6.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Leadcom 语音网络终端", None))
        self.label.setText(_translate("MainWindow", "连接状态:", None))
        self.label_2.setText(_translate("MainWindow", "软件版本:", None))
        self.btnCheckVersion.setText(_translate("MainWindow", "最新版本...", None))
        self.label_21.setText(_translate("MainWindow", "话机USB状态:", None))
        self.txtPhoneStatus.setText(_translate("MainWindow", "离线", None))
        self.label_23.setText(_translate("MainWindow", "磁盘空间", None))
        self.btnOpenMediaDir.setText(_translate("MainWindow", "打开录音目录", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("MainWindow", "状 态", None))
        self.btnClientQuery.setText(_translate("MainWindow", "搜 索", None))
        self.label_12.setText(_translate("MainWindow", "查找", None))
        self.btnClientDelete.setText(_translate("MainWindow", "删除", None))
        self.btnClientNew.setText(_translate("MainWindow", "新客户", None))
        self.btnClientEdit.setText(_translate("MainWindow", "编辑", None))
        self.btnDial.setText(_translate("MainWindow", "拨号", None))
        self.btnHangup.setText(_translate("MainWindow", "挂机", None))
        self.label_22.setText(_translate("MainWindow", "客户类别", None))
        self.btnSceneRecordStart.setText(_translate("MainWindow", "开始录音", None))
        self.btnSceneRecordStop.setText(_translate("MainWindow", "停止录音", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabClients), _translate("MainWindow", "客户信息", None))
        self.label_15.setText(_translate("MainWindow", "时  间", None))
        self.label_16.setText(_translate("MainWindow", "-", None))
        self.label_14.setText(_translate("MainWindow", "来去电类型", None))
        self.label_13.setText(_translate("MainWindow", "搜索条件", None))
        self.btnToneQuery.setText(_translate("MainWindow", "搜 索", None))
        self.dtToneStart.setDisplayFormat(_translate("MainWindow", "yyyy-M-d H:mm:ss", None))
        self.dtToneEnd.setDisplayFormat(_translate("MainWindow", "yyyy-M-d H:mm:ss", None))
        self.label_17.setText(_translate("MainWindow", "备注/产品ID/客户经理", None))
        self.btnRecordDial.setText(_translate("MainWindow", "拨 号", None))
        self.label_19.setText(_translate("MainWindow", "通话类型", None))
        self.txtPlayIndicator.setText(_translate("MainWindow", "00:00:00 / 00:00:00", None))
        self.btnToneMemo.setText(_translate("MainWindow", "备注信息", None))
        self.label_18.setText(_translate("MainWindow", "通话时间:", None))
        self.label_20.setText(_translate("MainWindow", "电话号码:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabArchives), _translate("MainWindow", "通话记录", None))
        self.groupBox.setTitle(_translate("MainWindow", "注册信息", None))
        self.label_3.setText(_translate("MainWindow", "注册名称", None))
        self.label_7.setText(_translate("MainWindow", "密  码", None))
        self.btnChangePasswd.setText(_translate("MainWindow", "修改密码", None))
        self.txtRegStatus.setText(_translate("MainWindow", "未注册", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "附属信息", None))
        self.label_4.setText(_translate("MainWindow", "电话号码", None))
        self.label_8.setText(_translate("MainWindow", "员工名称", None))
        self.label_9.setText(_translate("MainWindow", "地址信息", None))
        self.label_10.setText(_translate("MainWindow", "附属信息", None))
        self.label_6.setText(_translate("MainWindow", "分支机构:", None))
        self.btnUpdateTermInfo.setText(_translate("MainWindow", "修改终端信息", None))
        self.btnSave.setText(_translate("MainWindow", "保 存", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "服务器信息", None))
        self.label_5.setText(_translate("MainWindow", "服务器1", None))
        self.edtServer1.setText(_translate("MainWindow", "localhost:8000", None))
        self.edtServer2.setText(_translate("MainWindow", "localhost:2300", None))
        self.label_11.setText(_translate("MainWindow", "服务器2", None))
        self.ckAutoStartWithOsStart.setText(_translate("MainWindow", "随windows启动自动运行", None))
        self.ckAutoLogin.setText(_translate("MainWindow", "自动登陆", None))
        self.btnLogin.setText(_translate("MainWindow", "连接测试", None))
        self.ckRunInBackground.setText(_translate("MainWindow", "后台运行", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "话机设置", None))
        self.label_24.setText(_translate("MainWindow", "话机密码", None))
        self.label_25.setText(_translate("MainWindow", "锁屏时间", None))
        self.ckMemoAutoShow.setText(_translate("MainWindow", "自动显示通话备注", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("MainWindow", "系统设置", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRunLog), _translate("MainWindow", "运行日志", None))
        self.menu.setTitle(_translate("MainWindow", "系统", None))
        self.menu_5.setTitle(_translate("MainWindow", "高级", None))
        self.menu_2.setTitle(_translate("MainWindow", "帮助", None))
        self.menu_3.setTitle(_translate("MainWindow", "客户", None))
        self.menu_4.setTitle(_translate("MainWindow", "视图", None))
        self.menu_6.setTitle(_translate("MainWindow", "语音", None))
        self.miUserMgr.setText(_translate("MainWindow", "用户管理", None))
        self.miTask.setText(_translate("MainWindow", "计划任务", None))
        self.miServerStatus.setText(_translate("MainWindow", "服务器状态", None))
        self.miChangePwd.setText(_translate("MainWindow", "更改用户密码", None))
        self.miExit.setText(_translate("MainWindow", "系统退出", None))
        self.actionExit.setText(_translate("MainWindow", "退出", None))
        self.actClientImport.setText(_translate("MainWindow", "导入", None))
        self.actClientExport.setText(_translate("MainWindow", "导出", None))
        self.action_4.setText(_translate("MainWindow", "新客户", None))
        self.action_5.setText(_translate("MainWindow", "编辑", None))
        self.action_6.setText(_translate("MainWindow", "删除", None))
        self.actTabStatus.setText(_translate("MainWindow", "状态", None))
        self.actTabClient.setText(_translate("MainWindow", "客户信息", None))
        self.actTabArchive.setText(_translate("MainWindow", "通话记录", None))
        self.action_13.setText(_translate("MainWindow", "通话记录", None))
        self.actTabSettings.setText(_translate("MainWindow", "系统设置", None))
        self.actAbout.setText(_translate("MainWindow", "关于", None))
        self.actClientSyncFromServer.setText(_translate("MainWindow", "同步客户资料到本地", None))
        self.actSyncReset.setText(_translate("MainWindow", "话机同步复位", None))
        self.actArchiveUnMatched.setText(_translate("MainWindow", "未匹配客户的语音记录", None))
        self.actArchiveUnMatchedMutli.setText(_translate("MainWindow", "匹配到多客户的语音记录", None))
        self.actArchiveExport.setText(_translate("MainWindow", "导出通话记录", None))
        self.actLockPasswdSetting.setText(_translate("MainWindow", "锁屏设置", None))
        self.actLock.setText(_translate("MainWindow", "锁屏", None))

from PyQt4 import phonon
